import { AnswerOption, Category, Question } from "./types";
import { naOption } from "./scoring";

// IT path: 4-level maturity scale.
export const itAnswerScale: AnswerOption[] = [
  { value: "none", label: "Not implemented", credit: 0 },
  { value: "partial", label: "Partially", credit: 0.34 },
  { value: "largely", label: "Largely", credit: 0.67 },
  { value: "full", label: "Fully", credit: 1 },
];

// Standards summarised in the results matrix.
export const IT_STANDARDS = ["NZISM", "PSR", "Essential Eight", "ISO 27001", "HISF"];

export const itCategories: Category[] = [
  {
    id: "governance",
    ownerLabel: "Governance & Risk",
    description: "Policy, risk management, accountability and supplier assurance.",
    threat:
      "Without governance, security decisions are ad hoc and gaps go unowned until an incident exposes them.",
  },
  {
    id: "identity",
    ownerLabel: "Identity & Access Control",
    description: "Authentication, privilege, least-privilege and account lifecycle.",
    threat:
      "Weak access control lets one stolen credential become full compromise of systems and data.",
  },
  {
    id: "vulnmgmt",
    ownerLabel: "Patch & Vulnerability Management",
    description: "Timely patching, scanning and removal of unsupported systems.",
    threat:
      "Unpatched, internet-facing systems are the most exploited path into organisations.",
  },
  {
    id: "hardening",
    ownerLabel: "Application Control & Hardening",
    description: "Allow-listing, macro and application hardening, secure baselines.",
    threat:
      "Without hardening and application control, malware and untrusted code run freely on endpoints.",
  },
  {
    id: "dataprotection",
    ownerLabel: "Data Protection & Privacy",
    description: "Encryption, classification, Privacy Act 2020 and health information handling.",
    threat:
      "Unprotected personal or health data exposes you to Privacy Act 2020 breaches and HISF non-compliance.",
  },
  {
    id: "backup",
    ownerLabel: "Backup & Recovery",
    description: "Regular, isolated, tested backups and recovery objectives.",
    threat:
      "Without tested, isolated backups, ransomware or failure can cause permanent data loss.",
  },
  {
    id: "monitoring",
    ownerLabel: "Logging, Monitoring & Detection",
    description: "Central logging, retention, alerting and active review.",
    threat:
      "Without centralised logging and monitoring, attackers can operate undetected for weeks or months.",
  },
  {
    id: "incident",
    ownerLabel: "Incident Response & Continuity",
    description: "Response planning, exercises, reporting and business continuity.",
    threat:
      "Without a practised plan, a containable incident becomes prolonged, costly and damaging.",
  },
  {
    id: "network",
    ownerLabel: "Network & Boundary Security",
    description: "Segmentation, perimeter firewalls, secure remote access and email authentication.",
    threat:
      "Flat networks and weak boundaries let one compromised host or spoofed email spread across the whole environment.",
  },
];

const m = (
  id: string,
  categoryId: string,
  standards: string[],
  text: string,
  helpText: string,
  recommendation: string,
  weight = 1
): Question => ({ id, categoryId, kind: "maturity", weight, standards, text, helpText, recommendation });

export const itQuestions: Question[] = [
  // ---- Governance & Risk ----
  m("gov_policy", "governance", ["PSR", "ISO 27001", "NZISM"],
    "Do you have documented, approved information security policies that are reviewed on a regular cycle?",
    "PSR and ISO 27001 expect a governing policy set with clear ownership and review.",
    "Establish and regularly review approved information security policies."),
  m("gov_risk", "governance", ["PSR", "ISO 27001", "NZISM"],
    "Do you maintain a security risk register where risks are assessed, treated and reviewed?",
    "Risk management is the backbone of NZISM and ISO 27001.",
    "Stand up a risk register with regular assessment and treatment."),
  m("gov_roles", "governance", ["PSR", "ISO 27001"],
    "Are security roles and responsibilities (e.g. a security lead / CISO) formally assigned?",
    "PSR requires named accountability for protective security.",
    "Assign and document accountable security roles."),
  m("gov_thirdparty", "governance", ["ISO 27001", "NZISM", "PSR"],
    "Do you assess the security of third-party suppliers and cloud services before and during use?",
    "Supply-chain risk is a core NZISM and ISO 27001 control area.",
    "Introduce supplier security assessments and contractual security controls."),
  m("gov_asset", "governance", ["NZISM", "ISO 27001", "HISF"],
    "Do you maintain an up-to-date inventory of information assets together with their classification?",
    "You can't protect what you haven't identified and classified.",
    "Build and maintain a classified asset inventory."),
  { ...m("gov_sdlc", "governance", ["ISO 27001", "NZISM"],
    "If you build or customise software, is a secure development lifecycle applied (code review, dependency/SCA scanning, secrets management, separated environments)?",
    "ISO 27001 and NZISM expect security to be built into development, not bolted on after release. Choose \"Doesn't apply\" if you don't develop software.",
    "Adopt a secure software development lifecycle with code review, dependency scanning and secrets management."),
    scale: [...itAnswerScale, naOption] },
  m("gov_ai", "governance", ["ISO 27001", "PSR"],
    "Do you govern staff use of public AI tools and unsanctioned SaaS (shadow IT), with guidance on what data may be shared?",
    "Generative AI and shadow IT can leak sensitive data outside your control; governance is an emerging expectation.",
    "Set an acceptable-use policy for AI tools and discover/govern shadow-IT SaaS."),

  // ---- Identity & Access Control ----
  m("id_mfa", "identity", ["Essential Eight", "NZISM", "ISO 27001"],
    "Is phishing-resistant or app-based MFA enforced on all remote access, administrative and privileged accounts?",
    "Essential Eight lists MFA as a core mitigation; NZISM mandates it for privileged and remote access.",
    "Enforce MFA on all remote, admin and privileged access.", 2),
  m("id_privileged", "identity", ["Essential Eight", "NZISM", "ISO 27001"],
    "Are privileged accounts restricted, separated from daily-use accounts, and reviewed regularly?",
    "Essential Eight 'restrict admin privileges' limits the blast radius of a compromise.",
    "Restrict and review privileged accounts; separate admin from standard use."),
  m("id_rbac", "identity", ["NZISM", "ISO 27001", "HISF"],
    "Is access granted on least-privilege / role-based principles and recertified periodically?",
    "Least privilege is fundamental in NZISM and ISO 27001; HISF stresses it for health data.",
    "Apply least-privilege RBAC with periodic access recertification."),
  m("id_lifecycle", "identity", ["ISO 27001", "NZISM"],
    "Are joiner/mover/leaver processes in place so access is provisioned and revoked promptly?",
    "Orphaned accounts are a common and avoidable breach vector.",
    "Automate joiner/mover/leaver access provisioning and revocation."),
  m("id_passwords", "identity", ["NZISM", "ISO 27001"],
    "Do you enforce strong authentication (length, breached-password checks, no shared accounts)?",
    "NZISM sets authentication requirements; shared accounts destroy accountability.",
    "Enforce modern password policy and eliminate shared accounts."),

  // ---- Patch & Vulnerability Management ----
  m("vm_patch_os", "vulnmgmt", ["Essential Eight", "NZISM"],
    "Are operating systems patched within risk-based timeframes (e.g. critical internet-facing within 48 hours)?",
    "Essential Eight 'patch operating systems' targets rapid remediation of critical vulnerabilities.",
    "Patch operating systems on a risk-based SLA, prioritising internet-facing and critical hosts.", 2),
  m("vm_patch_apps", "vulnmgmt", ["Essential Eight", "NZISM"],
    "Are applications (browsers, Office, PDF readers, internet-facing apps) patched promptly?",
    "Essential Eight 'patch applications' is one of the highest-value mitigations.",
    "Patch applications promptly, prioritising exploitable internet-facing software."),
  m("vm_scan", "vulnmgmt", ["NZISM", "ISO 27001"],
    "Do you run regular authenticated vulnerability scans and track remediation through to closure?",
    "Scanning provides assurance that patching SLAs are actually being met.",
    "Run regular authenticated vulnerability scans with tracked remediation."),
  m("vm_eol", "vulnmgmt", ["NZISM", "ISO 27001"],
    "Are unsupported / end-of-life systems removed, isolated, or covered by compensating controls?",
    "End-of-life systems receive no security fixes and must be managed as elevated risk.",
    "Remove or isolate end-of-life systems that no longer receive vendor support."),
  m("vm_pentest", "vulnmgmt", ["NZISM", "ISO 27001", "PSR"],
    "Do you commission independent penetration tests of key systems periodically?",
    "NZISM and PSR expect independent assurance for important systems.",
    "Schedule periodic independent penetration testing of key systems."),

  // ---- Application Control & Hardening ----
  m("hd_appcontrol", "hardening", ["Essential Eight", "NZISM"],
    "Is application control / allow-listing enforced on workstations and servers?",
    "Essential Eight 'application control' is a strong defence against malware execution.",
    "Deploy application control (allow-listing) on endpoints and servers."),
  m("hd_macros", "hardening", ["Essential Eight", "NZISM"],
    "Are Microsoft Office macros disabled, or restricted to vetted and signed macros only?",
    "Essential Eight 'restrict Office macros' closes a common malware delivery path.",
    "Block or restrict Office macros to signed and trusted sources."),
  m("hd_browser", "hardening", ["Essential Eight", "NZISM"],
    "Are user applications hardened (blocking web ads, untrusted Java/Flash, unneeded features)?",
    "Essential Eight 'user application hardening' reduces drive-by attack surface.",
    "Harden browsers and user applications per Essential Eight guidance."),
  m("hd_baseline", "hardening", ["NZISM", "ISO 27001", "HISF"],
    "Do you build systems from documented secure configuration baselines (e.g. CIS / NZISM hardening)?",
    "NZISM provides hardening guidance; baselines prevent insecure defaults.",
    "Adopt and enforce secure configuration baselines for system builds."),
  m("hd_endpoint", "hardening", ["NZISM", "ISO 27001"],
    "Is modern endpoint protection (EDR / anti-malware) deployed, updated and monitored everywhere?",
    "Endpoint detection catches threats that slip past preventive controls.",
    "Deploy and monitor EDR / anti-malware across all endpoints."),
  m("hd_mdm", "hardening", ["NZISM", "ISO 27001", "HISF"],
    "Are mobile and BYOD devices managed (MDM / UEM) with enforced encryption, policy, separation of work data and remote wipe?",
    "Unmanaged mobile devices holding work and health data are a common, avoidable exposure.",
    "Enforce MDM / UEM with encryption, policy and remote wipe on mobile and BYOD devices."),
  m("hd_cloud", "hardening", ["NZISM", "ISO 27001"],
    "Are cloud and SaaS tenants hardened to a benchmark (e.g. CIS, Microsoft 365 Secure Score) and reviewed regularly?",
    "Default cloud configurations are rarely secure; benchmarks close the common misconfigurations attackers exploit.",
    "Harden cloud / SaaS tenants to a recognised benchmark and review configuration regularly."),

  // ---- Data Protection & Privacy ----
  m("dp_transit", "dataprotection", ["NZISM", "ISO 27001", "HISF"],
    "Is data encrypted in transit (TLS) across internal and external connections?",
    "NZISM mandates approved encryption for data in transit.",
    "Enforce TLS for all data in transit."),
  m("dp_rest", "dataprotection", ["NZISM", "ISO 27001", "HISF"],
    "Is sensitive and personal data encrypted at rest (disks, databases, backups)?",
    "Encryption at rest limits exposure if storage or backups are stolen.",
    "Encrypt sensitive and personal data at rest, including backups."),
  m("dp_classification", "dataprotection", ["NZISM", "PSR", "HISF"],
    "Is data classified and handled according to its sensitivity, including health information?",
    "PSR/NZISM classification and HISF drive appropriate handling of health information.",
    "Classify data and apply handling rules based on sensitivity."),
  m("dp_privacy", "dataprotection", ["HISF", "PSR"],
    "Do you meet Privacy Act 2020 obligations, including breach assessment and notification readiness?",
    "The Privacy Act 2020 requires notifying the Privacy Commissioner of breaches that cause serious harm.",
    "Operationalise Privacy Act 2020 breach assessment and notification."),
  m("dp_dlp", "dataprotection", ["NZISM", "ISO 27001", "HISF"],
    "Do you control data egress (DLP, restricted USB / cloud uploads) for sensitive information?",
    "Egress controls reduce both deliberate exfiltration and accidental disclosure.",
    "Introduce data-loss-prevention controls on sensitive data egress."),

  // ---- Backup & Recovery ----
  m("bk_backups", "backup", ["Essential Eight", "NZISM", "ISO 27001"],
    "Are important data and system configurations backed up on a defined, regular schedule?",
    "Essential Eight 'regular backups' underpins ransomware recovery.",
    "Back up important data and configurations on a regular schedule.", 2),
  m("bk_immutable", "backup", ["Essential Eight", "NZISM"],
    "Is at least one backup copy kept offline, immutable, or otherwise isolated from production?",
    "Modern ransomware targets connected backups; isolation preserves recoverability.",
    "Keep an offline / immutable backup copy isolated from production."),
  m("bk_restore", "backup", ["Essential Eight", "NZISM", "ISO 27001"],
    "Do you test restoration of backups regularly and record the results?",
    "Untested backups frequently fail when needed; Essential Eight requires testing.",
    "Run and document regular restore tests."),
  m("bk_objectives", "backup", ["ISO 27001", "NZISM", "HISF"],
    "Are recovery time and recovery point objectives (RTO / RPO) defined for critical systems?",
    "Recovery objectives turn 'we have backups' into measurable resilience.",
    "Define and validate RTO / RPO for critical systems."),
  m("bk_dr", "backup", ["ISO 27001", "NZISM", "PSR"],
    "Do you have a disaster recovery plan that is documented and exercised?",
    "A tested DR plan limits downtime when systems fail.",
    "Document and exercise a disaster recovery plan."),

  // ---- Logging, Monitoring & Detection ----
  m("mn_logging", "monitoring", ["NZISM", "ISO 27001"],
    "Are security-relevant logs centrally collected from systems, endpoints and cloud services?",
    "NZISM requires event logging; central collection is what enables detection.",
    "Centralise security logging across systems, endpoints and cloud."),
  m("mn_retention", "monitoring", ["NZISM", "ISO 27001", "HISF"],
    "Are logs retained for an appropriate period and protected from tampering?",
    "Tamper-evident retention supports investigations and compliance.",
    "Retain and protect logs in line with policy and standards."),
  m("mn_alerting", "monitoring", ["NZISM", "ISO 27001"],
    "Do you have alerting / SIEM that detects and triages suspicious activity?",
    "Detection turns raw logs into timely response.",
    "Implement alerting / SIEM with triage for suspicious activity."),
  m("mn_review", "monitoring", ["NZISM", "ISO 27001", "PSR"],
    "Are alerts and logs actively reviewed by staff or a monitored service (SOC / MSSP)?",
    "Collecting logs adds no value if no one reviews them.",
    "Ensure logs and alerts are actively monitored, in-house or via an MSSP / SOC."),
  m("mn_identity", "monitoring", ["NZISM", "ISO 27001"],
    "Do you monitor identity, email and cloud activity (impossible-travel, mass download, risky sign-ins)?",
    "Most modern attacks traverse identity and cloud, not just the network.",
    "Extend monitoring to identity, email and cloud activity."),

  // ---- Incident Response & Continuity ----
  m("ir_plan", "incident", ["NZISM", "ISO 27001", "PSR", "HISF"],
    "Do you have a documented incident response plan with defined roles and severity levels?",
    "A written IR plan prevents improvised, error-prone responses under pressure.",
    "Document an incident response plan with clear roles and severity levels."),
  m("ir_exercise", "incident", ["NZISM", "ISO 27001", "PSR"],
    "Do you exercise the incident response plan (tabletop or simulation) at least annually?",
    "Exercises expose gaps before a real incident does.",
    "Run at least annual incident response exercises."),
  m("ir_report", "incident", ["PSR", "HISF", "NZISM"],
    "Do staff know how and when to report incidents to the NCSC (which now includes the former CERT NZ) and the Privacy Commissioner?",
    "New Zealand has expected reporting channels, and the Privacy Act mandates some notifications.",
    "Define external reporting paths (the NCSC, formerly CERT NZ, and the Privacy Commissioner)."),
  m("ir_contain", "incident", ["NZISM", "ISO 27001"],
    "Can you rapidly contain incidents (isolate hosts, revoke access, rotate credentials)?",
    "Fast containment limits the spread and the cost of an incident.",
    "Prepare rapid containment capabilities such as host isolation and access revocation."),
  m("ir_bcp", "incident", ["ISO 27001", "PSR", "HISF"],
    "Is there a business continuity plan so critical services continue during a major disruption?",
    "Continuity planning keeps essential services running during a crisis.",
    "Maintain a business continuity plan for critical services."),

  // ---- Network & Boundary Security ----
  m("net_segmentation", "network", ["NZISM", "ISO 27001"],
    "Are networks segmented (VLANs / security zones) to contain lateral movement, with management interfaces isolated?",
    "Segmentation is an NCSC Critical Control and limits how far an intruder or ransomware can spread from a single foothold.",
    "Segment networks into zones and isolate management interfaces to contain lateral movement.", 2),
  m("net_boundary", "network", ["NZISM", "ISO 27001"],
    "Are perimeter firewalls and secure remote access (VPN / ZTNA) enforced, with ingress/egress filtering reviewed?",
    "NZISM requires controlled network boundaries; unfiltered egress is a common data-exfiltration and C2 path.",
    "Enforce perimeter firewalls and secure remote access, and review ingress/egress filtering."),
  m("net_email_auth", "network", ["NZISM", "ISO 27001"],
    "Are SPF, DKIM and DMARC (with DMARC at enforce/reject) deployed across all sending domains?",
    "Email authentication stops domain spoofing; DMARC enforcement is increasingly mandated for NZ organisations.",
    "Deploy SPF, DKIM and DMARC at enforcement across all sending domains."),
];
